# Use "make defconfig" to generate a complete .config file

# Custom firmware base
# echo 'CONFIG_TARGET_x86=y' >> $BUILDROOT/.config
# echo 'CONFIG_TARGET_x86_64=y' >> $BUILDROOT/.config
# echo 'CONFIG_TARGET_x86_64_DEVICE_generic=y' >> $BUILDROOT/.config
# echo 'CONFIG_TARGET_ROOTFS_PARTSIZE=3072' >> $BUILDROOT/.config

#echo 'CONFIG_TARGET_mediatek=y' >> $BUILDROOT/.config
#echo 'CONFIG_TARGET_mediatek_filogic=y' >> $BUILDROOT/.config
#echo 'CONFIG_TARGET_mediatek_filogic_DEVICE_bananapi_bpi-r3-mini=y' >> $BUILDROOT/.config

# Lanuage Setting
#echo 'CONFIG_LUCI_LANG_zh_Hans=y' >> $BUILDROOT/.config

# Add OpenClash
#echo '# CONFIG_PACKAGE_dnsmasq is not set' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-openclash=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-compat=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_wget-ssl=y' >> $BUILDROOT/.config

# Add Docker
#echo 'CONFIG_PACKAGE_luci-app-dockerman=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_dockerd=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_docker-compose=y' >> $BUILDROOT/.config

# Add other apps
#echo 'CONFIG_PACKAGE_luci=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-ssl=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-wol=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-aria2=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-samba4=y' >> $BUILDROOT/.config

# QCN550x apjet01 board
echo 'CONFIG_TARGET_ath79=y' >> $BUILDROOT/.config
echo 'CONFIG_TARGET_ath79_generic=y' >> $BUILDROOT/.config
echo 'CONFIG_TARGET_ath79_generic_DEVICE_asus_rt-ac59u=y' >> $BUILDROOT/.config
echo 'CONFIG_BATMAN_ADV_BATMAN_V=y' >> $BUILDROOT/.config
echo 'CONFIG_BATMAN_ADV_BLA=y' >> $BUILDROOT/.config
echo 'CONFIG_BATMAN_ADV_DAT=y' >> $BUILDROOT/.config
echo 'CONFIG_BATMAN_ADV_MCAST=y' >> $BUILDROOT/.config
echo 'CONFIG_BATMAN_ADV_NC=y' >> $BUILDROOT/.config
#echo 'CONFIG_GETDNS_ENABLE_STUB_ONLY=y' >> $BUILDROOT/.config  #unbound
#echo 'CONFIG_OPENSSL_ENGINE=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_ASM=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_CMS=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_DEPRECATED=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_IDEA=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_MDC2=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_PSK=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_SEED=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_SRP=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_TLS13=y' >> $BUILDROOT/.config
#echo 'CONFIG_OPENSSL_WITH_WHIRLPOOL=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_batctl-default=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_block-mount=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_cgi-io=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_coreutils=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_e2fsprogs=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_gawk=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_getdns=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_htop=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_ip-tiny=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_ip6tables-nft=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_ipset=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_iptables-mod-conntrack-extra=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_iptables-mod-ipopt=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_iptables-nft=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_irqbalance=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-batman-adv=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-crypto-kpp=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-fs-ext4=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ifb=y' >> $BUILDROOT/.config #sqm
#echo 'CONFIG_PACKAGE_kmod-ip6tables=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ipt-conntrack=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ipt-core=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ipt-ipopt=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ipt-ipset=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-lib-crc16=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-lp=y' >> $BUILDROOT/.config #parallel port
echo 'CONFIG_PACKAGE_kmod-mii=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-nf-conncount=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-nf-ipt=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-nf-ipt6=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-nft-compat=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-ppdev=y' >> $BUILDROOT/.config #parallel port
#echo 'CONFIG_PACKAGE_kmod-sched-cake=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-sched-core=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-scsi-core=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-udptunnel4=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_kmod-udptunnel6=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-usb-net=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-usb-net-rndis=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-usb-printer=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-usb-storage=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-usb-storage-uas=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_kmod-wireguard=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libatomic=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libblkid=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libcap=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libcomerr=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libevdev=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libext2fs=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libipset=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libiptext=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libiptext-nft=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libiptext6=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_liblua=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_liblucihttp=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_liblucihttp-lua=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_liblucihttp-ucode=y' >> $BUILDROOT/.config
echo '# CONFIG_PACKAGE_libmbedtls is not set' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libncurses=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libopenssl=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libopenssl-conf=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libopenssl-legacy=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libparted=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libpcre2=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libreadline=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_librt=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libss=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libubus-lua=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libudev-zero=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libusb-1.0=y' >> $BUILDROOT/.config
echo '# CONFIG_PACKAGE_libustream-mbedtls is not set' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libustream-openssl=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_libuuid=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libuv=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libwebsockets-full=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libxtables=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_libyaml=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_lua=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-firewall=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-mwan3=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-nextdns=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-app-opkg=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-app-p910nd=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-app-sqm=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-app-ttyd=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-app-wifischedule=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-base=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-compat=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-lib-base=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-lib-ip=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-lib-jsonc=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-lib-nixio=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-light=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-lua-runtime=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-mod-admin-full=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-mod-network=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-mod-status=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-mod-system=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-proto-batman-adv=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-proto-ipv6=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_luci-proto-ppp=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-proto-wireguard=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_luci-theme-bootstrap=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_mwan3=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_nextdns=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_p910nd=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_parted=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_rpcd=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_rpcd-mod-file=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_rpcd-mod-iwinfo=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_rpcd-mod-luci=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_rpcd-mod-rrdns=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_rpcd-mod-ucode=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_sqm-scripts=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_stubby=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_tc-tiny=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_terminfo=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_ttyd=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_ucode-mod-html=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_ucode-mod-lua=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_ucode-mod-math=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_uhttpd=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_uhttpd-mod-ubus=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_usbutils=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_wget-ssl=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_wifischedule=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_wireguard-tools=y' >> $BUILDROOT/.config
echo '# CONFIG_PACKAGE_wpad-basic-mbedtls is not set' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_wpad-openssl=y' >> $BUILDROOT/.config
#echo 'CONFIG_PACKAGE_xtables-nft=y' >> $BUILDROOT/.config
echo 'CONFIG_PACKAGE_zlib=y' >> $BUILDROOT/.config
echo 'CONFIG_PARTED_READLINE=y' >> $BUILDROOT/.config
echo 'CONFIG_WPA_MBO_SUPPORT=y' >> $BUILDROOT/.config
